### ISSUE TITLE
Combine outputs to post only a single comment

### ISSUE THREAD

**Issue by rchl** [lifeofguenter/terratalk#10]
Currently, the script is run separately for both stage and prod. What do you think about a mode where we would collect TF outputs into a variable (in the pipeline) and only run the script once both have completed, creating only one comment?

(Just looking for ways to limit the number of unnecessary notifications.)

**Comment by lifeofguenter** [comment]
could make sense, but unfortunately the plan-files can have a different `TF_DATA_DIR` each. So you would have to be able to pass that info through together with the "workspace" arg.

maybe something in future :)

**Comment by rchl** [comment]
I was more thinking to handle it in separate steps in the pipeline and then compose and post both results from following pipeline step. I don't expect you to work on that anymore tho :)
